### ISSUE TITLE
Put data repo in a submodule and remove it from history

### ISSUE THREAD

**Issue by hhirsch** [goblinhack/adventurine#1]
The data repo is mixed with the source code. This makes it really awkward to clone the repository. To fix this, data has to be moved into a submodule and removed from history. Sadly this will break the history. To preserve the history you can push the old repository that contains the source code and data to adventurine-history. It is better to break some things now than to have them broken for all eternity.

**Comment by goblinhack** [comment]
Hi - this is a new project - but a chance to do it better. My git fu is not
very advanced and have not worked with sub modules - any pointers
appreciated

**Comment by hhirsch** [comment]
@goblinhack Before you delete anything 
1.  create a copy of the current repo in another repository so that your history before moving the game data out lives on there
2. move the data to its own repository. The root of the repo will be exactly what goes into the directory when you add it as a submodule
3. either of the following should work to delete the directory from git http://dalibornasevic.com/posts/2-permanently-remove-files-and-folders-from-a-git-repository or https://rtyley.github.io/bfg-repo-cleaner/
4. Add the submodule in the directory https://chrisjean.com/git-submodules-adding-using-removing-and-updating/

If you create the backup repo there is nothing that can go wrong and you can test it very well before you push anything.

**Comment by goblinhack** [comment]
ok, all done!

```
git clone --recursive https://github.com/goblinhack/adventurine.git
```

pulls it all in one go now

**Comment by hhirsch** [comment]
@goblinhack I did the same thing for gorynlich but I think we talked about it and you rejected it so it never got merged. Continuation here: https://github.com/hhirsch/goblinhack2/commit/f93e6f30f2c8045225acbe00928e97e6bc33f802

**Comment by goblinhack** [comment]
I just lost heart with gorynlich - and wanted to move on to a new project
where I fix all the things I got wrong

sorry man

neil
